resources:
  - name: pipeline_trigger
    type: Artifact
    configuration:
      jfrogPlatformProvider: newAdminTokenIntegration
      repositories:
        - test-example-repo-local
      artifactPath:
        include:
          - tools/*
        exclude:
          - exclude/*
      buildOn:
        deployed: true
        cached: true
        deleted: true
        copied: true
        moved: true
      branches:
        include: master
        exclude: test
pipelines:
  - name: new_artifact_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: pipeline_trigger
        execution:
          onExecute:
            - echo "test"
